//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptBooking
    {
        public int id { get; set; }
        public string driver_name { get; set; }
        public string driver_mobile { get; set; }
        public string driver_gender { get; set; }
        public string rider_name { get; set; }
        public string rider_mobile { get; set; }
        public string rider_gender { get; set; }
        public Nullable<System.DateTime> booked_at { get; set; }
        public Nullable<System.DateTime> reached_at { get; set; }
        public Nullable<System.DateTime> start_at { get; set; }
        public Nullable<System.DateTime> end_at { get; set; }
        public Nullable<System.DateTime> canceled_at { get; set; }
        public Nullable<System.DateTime> accepted_at { get; set; }
        public Nullable<int> driver_rate { get; set; }
        public string from_plc { get; set; }
        public string to_plc { get; set; }
        public Nullable<decimal> seat_cost { get; set; }
        public string vehicle { get; set; }
        public string driver_id_no { get; set; }
        public string driver_license_no { get; set; }
        public int owner_id { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public int driver_id { get; set; }
        public int rider_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public int trip_share_details_id { get; set; }
        public int trip_request_details_id { get; set; }
        public Nullable<int> trip_type_id { get; set; }
        public string driver_email { get; set; }
        public string rider_email { get; set; }
        public Nullable<decimal> from_lat { get; set; }
        public Nullable<decimal> from_lng { get; set; }
        public Nullable<decimal> to_lat { get; set; }
        public Nullable<decimal> to_lng { get; set; }
    }
}
