//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_vehicles()
        {
            this.trip_share = new HashSet<trip_share>();
            this.tbl_drivers_vehicles_rel = new HashSet<tbl_drivers_vehicles_rel>();
        }
    
        public int id { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public int capacity { get; set; }
        public int owner_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public int created_by { get; set; }
        public string license_no { get; set; }
        public bool is_delete { get; set; }
    
        public virtual tbl_accounts tbl_accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trip_share> trip_share { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_drivers_vehicles_rel> tbl_drivers_vehicles_rel { get; set; }
    }
}
