//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_images
    {
        public int id { get; set; }
        public string model_name { get; set; }
        public int model_id { get; set; }
        public string model_tag { get; set; }
        public string thumb { get; set; }
        public string meduim { get; set; }
        public string large { get; set; }
        public string original { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> created_by { get; set; }
    }
}
