//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_setting
    {
        public int id { get; set; }
        public string setting_key { get; set; }
        public string setting_name { get; set; }
        public string setting_value { get; set; }
        public int setting_type { get; set; }
        public string datasource_url { get; set; }
        public string datasource_json { get; set; }
        public string setting_group { get; set; }
        public Nullable<bool> display { get; set; }
        public Nullable<int> sequance { get; set; }
    }
}
