//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_drivers_vehicles_rel
    {
        public int id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual tbl_accounts tbl_accounts { get; set; }
        public virtual tbl_vehicles tbl_vehicles { get; set; }
    }
}
