//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip_share
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trip_share()
        {
            this.trip_share_details = new HashSet<trip_share_details>();
        }
    
        public int id { get; set; }
        public int driver_id { get; set; }
        public Nullable<System.DateTime> start_at_date { get; set; }
        public Nullable<System.DateTime> end_at_date { get; set; }
        public Nullable<int> vehicle_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> trip_type_id { get; set; }
    
        public virtual tbl_accounts tbl_accounts { get; set; }
        public virtual tbl_vehicles tbl_vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trip_share_details> trip_share_details { get; set; }
        public virtual trip_types trip_types { get; set; }
    }
}
