//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProfile
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> register_time { get; set; }
        public Nullable<int> gender_id { get; set; }
        public string id_no { get; set; }
        public string driver_license_no { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string gender_name { get; set; }
        public string country_name { get; set; }
        public string city_name { get; set; }
        public int is_owner { get; set; }
        public int is_driver { get; set; }
        public string ID_Image { get; set; }
        public string DL_Image { get; set; }
        public string Profile_Image { get; set; }
        public string firebase_uid { get; set; }
        public Nullable<int> MyVehicles { get; set; }
        public Nullable<int> DriveVehicles { get; set; }
        public Nullable<int> MyDrivers { get; set; }
        public Nullable<decimal> rate_total { get; set; }
        public Nullable<int> rate_count { get; set; }
    }
}
