//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSeatsPending
    {
        public string from_plc { get; set; }
        public Nullable<decimal> from_lng { get; set; }
        public Nullable<decimal> from_lat { get; set; }
        public string to_plc { get; set; }
        public Nullable<decimal> to_lng { get; set; }
        public Nullable<decimal> to_lat { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> start_at_date { get; set; }
        public Nullable<int> seats { get; set; }
        public Nullable<int> booked_seats { get; set; }
        public string type { get; set; }
        public int acc_id { get; set; }
        public Nullable<int> trip_type_id { get; set; }
        public Nullable<decimal> seat_cost_from { get; set; }
        public Nullable<decimal> seat_cost_to { get; set; }
        public Nullable<decimal> seat_cost { get; set; }
    }
}
