//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTripSeatDetails
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string mobile { get; set; }
        public Nullable<int> gender_id { get; set; }
        public string gender_name { get; set; }
        public Nullable<decimal> seat_cost { get; set; }
        public Nullable<decimal> from_lat { get; set; }
        public Nullable<decimal> from_lng { get; set; }
        public string from_plc { get; set; }
        public Nullable<decimal> to_lat { get; set; }
        public Nullable<decimal> to_lng { get; set; }
        public string to_plc { get; set; }
        public Nullable<System.DateTime> booked_at { get; set; }
        public Nullable<System.DateTime> reached_at { get; set; }
        public Nullable<System.DateTime> start_at { get; set; }
        public Nullable<System.DateTime> end_at { get; set; }
        public Nullable<System.Guid> trip_token { get; set; }
        public int trip_id { get; set; }
        public int main_trip_id { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> canceled_at { get; set; }
        public Nullable<int> canceled_by { get; set; }
        public Nullable<System.DateTime> accepted_at { get; set; }
        public Nullable<int> accepted_by { get; set; }
        public string rider_firebase_id { get; set; }
        public string driver_firebase_id { get; set; }
        public string driver_first_name { get; set; }
        public string driver_last_name { get; set; }
        public string driver_mobile { get; set; }
        public Nullable<int> driver_gender_id { get; set; }
        public int rider_id { get; set; }
        public int driver_id { get; set; }
        public Nullable<System.Guid> guid { get; set; }
    }
}
