//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chair80CP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVehicles
    {
        public int id { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public int capacity { get; set; }
        public int owner_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public int created_by { get; set; }
        public string license_no { get; set; }
        public bool is_delete { get; set; }
        public string owner { get; set; }
        public Nullable<int> Drivers { get; set; }
        public Nullable<int> Trips { get; set; }
        public Nullable<int> Images { get; set; }
    }
}
